### ISSUE TITLE
gluttony does not work with recent pip

### ISSUE THREAD

**Issue by marscher** [fangpenlin/gluttony#2]
```
marscher@jigsaw:~$ gluttony 
Traceback (most recent call last):
  File "/home/marscher/.local/bin/gluttony", line 9, in <module>
    load_entry_point('Gluttony==0.8', 'console_scripts', 'gluttony')()
  File "/home/marscher/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 2457, in load_entry_point
    return ep.load()
  File "/home/marscher/anaconda/lib/python2.7/site-packages/pkg_resources.py", line 2171, in load
    ['__name__'])
  File "/home/marscher/.local/lib/python2.7/site-packages/gluttony/commands.py", line 7, in <module>
    from pip.log import logger
ImportError: No module named log
marscher@jigsaw:~$ pip --version
pip 6.0.8 from /home/marscher/anaconda/lib/python2.7/site-packages (python 2.7)
```

**Comment by foutoucour** [comment]
Same! need updates :(

**Comment by DomhnallBoyle** [comment]
Hi, has there been any progress on this issue? Currently doesn't work on pip version 8.1.2

**Comment by matiskay** [comment]
I confirm that it doesn't work with pip version pip 9.0.1.

**Comment by rdkdd** [comment]
It still does not work. Any progress?
